Add error message

diff --git a/git-branch-editor b/git-branch-editor
--- a/git-branch-editor
+++ b/git-branch-editor
@@ -3,8 +3,17 @@
 all=.git-branch-editor-all
 keep=.git-branch-editor-keep
 
+cleanup() {
+  rm $all $keep
+}
 
 git branch | grep -v '^*' | sed 's/^  //' | tee $all $keep > /dev/null
+
+if [ `cat $all | wc -l` == 0 ]; then
+  echo "No branches found to delete (cannot delete current branch)."
+  cleanup
+  exit 1
+fi
 
 eval $EDITOR $keep
 
@@ -12,7 +21,7 @@ delete=`diff --suppress-common-lines $all $keep | grep '^< ' | awk '{print $2}'`
 
 echo $delete | xargs git branch -D
 
-rm $all $keep
+cleanup()
 
 
 
